services:
  db:
    image: postgres:latest
    container_name: katalogcu_db
    environment:
      POSTGRES_USER: postgres      # BurasÄ± postgres kalsÄ±n
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: KatalogcuDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_new:/var/lib/postgresql/data  # ðŸ‘ˆ Ä°SMÄ° DEÄžÄ°ÅžTÄ°RDÄ°K!

volumes:
  pgdata_new:  # ðŸ‘ˆ BURAYI DA DEÄžÄ°ÅžTÄ°RDÄ°K!