services:
  db:
    # ðŸ‘‡ DEÄžÄ°ÅžÄ°KLÄ°K BURADA: Standart 'postgres' yerine 'pgvector' imajÄ±nÄ± kullanÄ±yoruz.
    # Bu imaj, PostgreSQL 16 Ã¼zerine kurulmuÅŸ pgvector eklentisini iÃ§erir.
    image: pgvector/pgvector:pg16
    container_name: katalogcu_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: KatalogcuDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_new:/var/lib/postgresql/data

volumes:
  pgdata_new: